In [1]:
import numpy as np

In [2]:
arr = np.arange(1,11)

In [3]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

9

In [5]:
arr[1:5]

array([2, 3, 4, 5])

In [6]:
arr[:5]

array([1, 2, 3, 4, 5])

In [7]:
arr[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
# Broadcasting

In [9]:
arr[0:5] = 100 # permanent change set 1 4 elements to 100

In [10]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [11]:
arr_deep_copy = arr.copy()

In [12]:
arr_deep_copy

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [13]:
arr[:3] = 300

In [14]:
arr

array([300, 300, 300, 100, 100,   6,   7,   8,   9,  10])

In [15]:
arr_deep_copy

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [17]:
mat = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [26]:
mat[1:][:2]

array([[20, 25, 30],
       [35, 40, 45]])

In [27]:
# Conditional selection

In [28]:
arr = np.arange(1,11)

In [29]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [31]:
bool_arr = arr > 4
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [32]:
arr[arr>7]

array([ 8,  9, 10])

In [33]:
arr[arr<=5]

array([1, 2, 3, 4, 5])