In [1]:
import numpy as np

In [2]:
# Creating Numpy array

In [3]:
my_list = [1,2,3]
x = np.array(my_list)
type(x)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3], [1,2,3],[1,2,3]]
np.array(my_matrix)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [10]:
np.arange(0,11, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
np.random.rand(3, 4)

array([[0.99109536, 0.722078  , 0.00553709, 0.68100565],
       [0.79847122, 0.32002595, 0.41818662, 0.74199966],
       [0.17123427, 0.36321885, 0.88805135, 0.51487246]])

In [27]:
 np.random.randn(3, 4)

array([[-1.31296681,  0.20555303, -0.05616319, -0.89870259],
       [ 0.13484788,  1.48762703, -0.24452034,  0.86963202],
       [-2.02278289, -0.35850482,  0.1124166 ,  0.66545042]])

In [29]:
np.random.randint(1, 100, 10)

array([76, 56, 37, 91, 10, 62, 40, 39, 64, 67])

In [50]:
arr = np.arange(30)
ranarr = np.random.randint(0,50, 30)
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [56]:
ranarr

array([ 8, 17,  7, 25, 37, 22, 43, 18,  4, 15, 12, 34,  9, 37, 29,  7,  2,
       44, 13, 41, 37, 15, 11, 22,  0, 38, 26, 32, 31, 48])

In [57]:
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [58]:
ranarr.reshape(10,3).shape

(10, 3)

In [59]:
ranarr.max()

48

In [60]:
ranarr.argmax()

29